### ISSUE TITLE
Glossary of Terms

### ISSUE THREAD

**Issue by shawntanzk** [jamesaoverton/obook#210]
I think something that we should have is a glossary of terms that people can refer to easily
Please contribute to things we should define: (currently not ordered but this defs should be order alphabetically or something)
Also I know this is gonna be a lot of fighting on what accurate definitions are, so I apologise for any insane arguments that happen through this lol >.< Probably also best to have a note in the documentation that this is our understanding of it or something like that 

- Individuals 
    - Named Individuals
    - Anonymouse Individuals
- Classes 
- Object Properties
- Annotation Properties
- Data Properties 
- Anonymous Ancestor
- Materialised 
- Nodes and Edges 
- Knowledge Graph (comparing with ontology)
- Controlled Vocabulary (comparing with ontology) 
- Data Model (compared to the above) 
- Triple Store
- Endpoint

**Comment by nicolevasilevsky** [comment]
I think it's a great idea to have a glossary for OBO Academy. I think a vocabulary specifically for OBO Academy would be best, as we may want to include terms that aren't relevant to OAK.

Could we just copy and paste what is in OAK into OBO Academy and extend it?

@shawntanzk I like the idea of a disclaimer too :)

@shawntanzk, I would be happy to help too.

**Comment by matentzn** [comment]
I am not worried about duplication and its fine to have two glossaries. I agree we need one here, for sure

**Comment by shawntanzk** [comment]
Sounds good! Will make a start on it soon (I say soon, but I'm on holiday next week so... lol). @nicolevasilevsky I would love help :) I think starting with a copy and paste of whats in OAK is a good place (@cmungall - is it alright if we flagrantly plagiarise your document?)

**Comment by cmungall** [comment]
And while I think separate voices are good, OAK-OBOOK consistency is important

One of my bugbears is one community to use a term like "ancestor" to mean one thing (e.g. OWL community => subClassOf ancestor) and another community to use it another thing (everyone else => ancestor = transitive closure of relation graph)

**Comment by matentzn** [comment]
Maybe more general terms can migrate to the OBOOK glossary which is likely to have a much larger scope.. and the OAK glossary can focus on specific terms required to understand the data models and otherwise link to the OBOOK GLOSSARY?

**Comment by cmungall** [comment]
plagiarize all you want, don't worry about attribution or anything like
that, but rather than copypasta, consider each term individually and try
and speak with one obo academy voice, which may be different from the OAK
voice

it may also be tempting to copypaste from e.g. W3 docs but consider if this
is really doing our community a service, it's better to go for internal
cohesion and consistency (but by all means provide links to external
resources)
