### ISSUE TITLE
Fix incorrect link for 'Install ELK 0.5'

### ISSUE THREAD

**Issue by rays22** [jamesaoverton/obook#53]
The incorrect link for [Install ELK 0.5](https://github.com/jamesaoverton/obook/blob/master/docs/howto/install_elk_0.5_protege.md) on page [Contributing to OBO ontologies ](https://github.com/OBOAcademy/obook/blob/master/docs/lesson/contributing_to_obo_ontologies.md)
should be changed to
<https://github.com/OBOAcademy/obook/blob/master/docs/howto/installing_elk_in_protege.md>
.
Line
```
- **[Install ELK 0.5](https://github.com/jamesaoverton/obook/blob/master/docs/howto/install_elk_0.5_protege.md)** 
```
should be replaced by
```
- **[Install ELK 0.5](https://github.com/OBOAcademy/obook/blob/master/docs/howto/installing_elk_in_protege.md** 
```
.

**Comment by rays22** [comment]
@matentzn : I have made a fork of the repo and a [pull request to fix the link.](https://github.com/OBOAcademy/obook/pull/54)
I do not have write access to this repo.

**Comment by paulacalipho** [comment]
In https://oboacademy.github.io/obook/lesson/contributing-to-obo-ontologies/#branch
the link to **Install ELK 0.5** (https://github.com/OBOAcademy/obook/blob/master/docs/howto/installing_elk_in_protege.md) does not work.
Sorry if is not the right place to report this issue

**Comment by matentzn** [comment]
Excellent, thank you @paulacalipho! We really appreciate your feedback. I have fixed the link! In 10 minutes it should be live on the site :)

**Comment by paulacalipho** [comment]
Many thanks, link works
